version: '3'

services:
  tomcat:
    build:
      context: ./.docker/tomcat
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
      - ./target/ROOT.war:/usr/local/tomcat/webapps/ROOT.war